### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by bkeepers** [integrations/html-to-mrkdwn#2]
Unfortunately, I don't think Slack supports images in message formatting.

**Comment by wilhelmklopp** [comment]
One thing we can do is attach one of the images (or especially if there is only one image) to the message using `image_url`: https://api.slack.com/docs/message-attachments#image_url

The current Slack integration seems to do this

**Comment by bkeepers** [comment]
Interesting. I like it.

I pushed a short-term fix to just include the images as links in #4

**Comment by esaruoho** [comment]
please let's get github - integration - to - slack working so that images are included when github posts it.
