### ISSUE TITLE
Strip language from ``` code fences 

### ISSUE THREAD

**Issue by bkeepers** [integrations/html-to-mrkdwn#3]
Leading `js` here should be stripped out of code fence:

![](https://user-images.githubusercontent.com/173/33627522-62354790-d9c3-11e7-8e9b-d20e6a16ee1c.png)

**Comment by 0000day** [comment]
This is not fixed yet. No highlighting and the language gets printed.

**Comment by SVaeth** [comment]
I am reproducing this issue in Java

**Comment by Preen** [comment]
+1

**Comment by mfish0005** [comment]
Yeah syntax highlighting would be nice.  The large corporation I work at is discussing switching to Discord mainly because of this issue

**Comment by JulianFerry** [comment]
+1

**Comment by ziofil** [comment]
bump!

**Comment by roffe** [comment]
bug back again?

![image](https://user-images.githubusercontent.com/5434736/188882729-ba4f508d-5426-481e-8d4b-bb6ac74e57cc.png)

**Comment by jgarite** [comment]
this is still not available as of Production 4.28.184 64-bit. would love to see some syntax highlighting. if i type:
/```html (without the leading slash)
the output becomes:

```
html               
<p>test</p> 
```

with no syntax highlighting (all code remains single color)

**Comment by boozedog** [comment]
+1

**Comment by spshauer** [comment]
+1

**Comment by MaverickMartyn** [comment]
How does Slack not support syntax highlighting yet?
It's such a basic feature to be missing in an otherwise very business- and developer-friendly tool.
There are plenty of open source solutions for this that could be implemented quickly. What's the hold up?

**Comment by stumash** [comment]
+1

**Comment by BrandonGillis** [comment]
+1
